### ISSUE TITLE
checklist for luminosity lesson/demo

### ISSUE THREAD

**Issue by tpmccauley** [cms-opendata-workshop/workshop-lesson-luminosity#1]
This issue it to collect and itemize things that need to be done for the luminosity lesson/demo. Checked means "done" in the sense that it's a minimum viable product ("alpha"?). These roughly correspond to parts of the lesson. Once they are done I will record a demo (gulp).

- [x] Introduction: what is luminosity, why is it important, and how is it measured?
- [x] How do I install brilcalc?
- [x] How do I calculate lumi myself?
